Add node size limit to MPT
0chain/common pull request #4
Opened 2022-09-11 14:44 UTC by uneet7

Fixes https://github.com/0chain/0chain/issues/1085

2022-09-11 19:53 UTC, boddumanohar commented on core/util/merkle_patricia_trie.go
> +		msg := fmt.Sprintf("node exceeds maximum permissible size, path: %s", string(path))
may be also specify the current length `len(eval)` and the maximum allowed limit `MPTMaxAllowableNodeSize` in the error message. So someone who reads the message of those limit.

2022-09-13 06:42 UTC, boddumanohar approved these changes
lgtm

2022-09-13 14:23 UTC, dabasov requested changes
lgtm

2022-09-13 14:23 UTC, dabasov approved these changes

2022-09-13 14:23 UTC, merged